name: Build Development

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
  EAS_PROJECT_ID: f345cdac-62b0-41d8-b7a4-5450aca69da5
  ENV_FILE: ${{ secrets.ENV_FILE }}

on:
  workflow_dispatch:
    inputs:
      skip_label:
        description: "라벨 체크 무시"
        type: boolean
        required: true
        default: false

jobs:
  check-label:
    if: inputs.skip_label != true
    uses: ./.github/workflows/label-checker.yml
    with:
      label: "build-native"

  build:
    needs: [check-label]
    if: |
      always() && (
        inputs.skip_label == true || 
        (needs.check-label.result == 'success' && needs.check-label.outputs.has_required_label == 'true')
      )
    runs-on: ubuntu-latest
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ env.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 9
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "pnpm"

      - name: 🏗 Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ env.EXPO_TOKEN }}

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Create .env file
        run: echo "${{ env.ENV_FILE }}" >> .env

      - name: 🔧 Initialize EAS Project
        run: yes | eas init --id ${{ env.EAS_PROJECT_ID }}

      - name: 🚀 Create Development Build - iOS
        id: ios-build
        uses: expo/expo-github-action/preview@v8
        with:
          command: command: |
            eas build --profile preview --platform ios --clear-cache --non-interactive --no-wait 2>&1 | 
            sed -E 's/(Serial Number) .*/\1 ********/g' | 
            sed -E 's/(Apple Team) [A-Z0-9]+ \((.*)\)/\1 ******** (\2)/g' | 
            sed -E 's/(Developer Portal ID) .*/\1 ********/g' | 
            sed -E 's/(UDID: )[0-9A-Z-]+/\1********/g' | 
            sed -E 's/(Bundle Identifier) .*/\1 ********/g' | 
            sed -E 's/@[^/]+\//@****\//g'
          comment: false

      - name: Get Build URL
        id: ios-build-url
        run: |
          BUILD_URL=$(eas build:list --status finished --platform ios --limit 1 --non-interactive | grep -o 'https://expo.dev/accounts/.*/builds/.*' | head -n 1)
          echo "build_url=$BUILD_URL" >> $GITHUB_OUTPUT

      - name: 💬 Notify Slack
        if: success()
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "text": "Native 앱 Preview 신규 버전 생성 알림",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "🎉 🎉 Native 앱 Development 빌드가 완료되었어요!\n\nPR: ${{ github.event.pull_request.html_url }}\nBranch: ${{ github.event.pull_request.head.ref }}\nDownload: ${{ steps.ios-build-url.outputs.build_url }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ env.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
